# Generated by Django 2.1 on 2020-07-29 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='题库名称', max_length=20)),
                ('choices', models.CharField(help_text='选择题数', max_length=5)),
                ('gaps', models.CharField(help_text='填空题数', max_length=5)),
                ('judges', models.CharField(help_text='判断题数', max_length=5)),
                ('num', models.CharField(help_text='此试卷使用次数', max_length=5)),
                ('popnum', models.CharField(help_text='总答题人数', max_length=5)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Course', verbose_name='所属分类')),
            ],
        ),
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(help_text='题目内容', max_length=200)),
                ('result', models.CharField(help_text='题目答案', max_length=200)),
                ('A', models.CharField(help_text='选项内容', max_length=200)),
                ('B', models.CharField(help_text='选项内容', max_length=200)),
                ('C', models.CharField(help_text='选项内容', max_length=200)),
                ('D', models.CharField(help_text='选项内容', max_length=200)),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.BankInfo', verbose_name='所属题库')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetailsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='比赛名称', max_length=20)),
                ('num', models.CharField(help_text='题目个数', max_length=3)),
                ('start_time', models.TimeField(auto_now_add=True, help_text='开始时间')),
                ('end_time', models.TimeField(auto_now_add=True, help_text='结束时间')),
                ('answer', models.TimeField(auto_now_add=True, help_text='答题时间')),
                ('total', models.CharField(help_text='总分', max_length=3)),
                ('partnum', models.CharField(help_text='参与人数', max_length=3)),
                ('details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.BankInfo', verbose_name='比赛分类')),
            ],
        ),
        migrations.CreateModel(
            name='gap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(help_text='题目内容', max_length=200)),
                ('result', models.CharField(help_text='题目答案', max_length=200)),
                ('true', models.CharField(help_text='选项内容', max_length=200)),
                ('false', models.CharField(help_text='选项内容', max_length=200)),
                ('gap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.BankInfo', verbose_name='所属题库')),
            ],
        ),
        migrations.CreateModel(
            name='judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(help_text='题目内容', max_length=200)),
                ('result', models.CharField(help_text='题目答案', max_length=200)),
                ('judge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.BankInfo', verbose_name='所属题库')),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, '未完成'), (2, '已完成'), (3, '超时')], help_text='答题状态')),
                ('issue_record', models.TextField(help_text='题目记录')),
                ('result_record', models.TextField(help_text='回答记录')),
                ('start_time', models.TimeField(auto_now_add=True, help_text='开始时间')),
                ('end_time', models.TimeField(auto_now_add=True, help_text='结束时间')),
                ('answer', models.TimeField(auto_now_add=True, help_text='用时')),
                ('true_num', models.CharField(help_text='正确数', max_length=3)),
                ('false_num', models.CharField(help_text='错误数', max_length=3)),
                ('goal', models.CharField(help_text='得分', max_length=3)),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.BankInfo', verbose_name='所属题库')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserInfo', verbose_name='所属用户')),
            ],
        ),
    ]
