# Generated by Django 2.1 on 2020-07-29 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, '编程类'), (2, '系统类'), (3, '框架类'), (4, '数据库类'), (5, '文科类'), (6, '理科类'), (7, '体育类'), (8, '面试题类')], help_text='分类名称')),
                ('head', models.CharField(default='http://img95.699pic.com/photo/40027/3434.jpg_wh300.jpg', help_text='分类Logo', max_length=200)),
                ('desc', models.TextField(help_text='分类描述')),
            ],
        ),
        migrations.CreateModel(
            name='OrganInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='机构名称', max_length=20)),
                ('password', models.CharField(help_text='机构用户密码', max_length=20)),
                ('head', models.CharField(default='http://img95.699pic.com/photo/40027/3434.jpg_wh300.jpg', help_text='机构校标', max_length=200)),
                ('desc', models.TextField(help_text='机构描述')),
                ('email', models.CharField(help_text='机构邮箱', max_length=20)),
                ('attn', models.CharField(help_text='联系人', max_length=20)),
                ('phone', models.CharField(help_text='联系电话', max_length=11)),
                ('site', models.TextField(help_text='机构地址')),
                ('type', models.IntegerField(choices=[(1, '培训机构'), (2, '高校'), (3, '个人院校'), (4, '名校')], help_text='机构类型')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='organ_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.OrganInfo', verbose_name='所属机构'),
        ),
    ]
