# Generated by Django 2.1 on 2020-07-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='用户姓名', max_length=20)),
                ('password', models.CharField(help_text='用户密码', max_length=20)),
                ('sex', models.IntegerField(choices=[(1, '男'), (0, '女'), (2, '未知')], default=2, help_text='用户性别')),
                ('age', models.IntegerField(default=0, help_text='用户年龄')),
                ('head', models.CharField(default='http://img95.699pic.com/photo/40027/3434.jpg_wh300.jpg', help_text='头像字段', max_length=200)),
                ('email', models.CharField(help_text='用户邮箱', max_length=50)),
                ('status', models.IntegerField(choices=[(0, '未验证'), (1, '已激活')], default=0, help_text='邮箱验证状态')),
                ('phone', models.CharField(help_text='用户手机号', max_length=11)),
                ('card', models.CharField(help_text='用户身份证', max_length=18)),
                ('school', models.CharField(help_text='所属院校', max_length=20)),
                ('src', models.IntegerField(choices=[(1, '微博授权用户'), (2, '游客用户'), (3, '普通用户'), (4, '机构用户')], default=2, help_text='用户类别')),
            ],
        ),
    ]
